# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0017_auto_20180611_1320'),
        ('cursos', '0018_auto_20180522_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situcao', models.CharField(default='Matriculado', max_length=100)),
                ('horas_faltadas', models.IntegerField(default=0)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.Aluno')),
            ],
        ),
        migrations.AlterField(
            model_name='turma',
            name='alunos_inscritos',
            field=models.ManyToManyField(related_name='turma_Aluno_inscrito', to='cursos.Matricula'),
        ),
    ]
