# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-13 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0021_auto_20180912_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turma',
            name='pauta',
        ),
        migrations.AddField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Fechado', 'Fechado')], default='Aberto', max_length=25, verbose_name='Status'),
        ),
    ]
