# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0022_auto_20180913_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='status',
            field=models.CharField(choices=[('Aberta', 'Aberta'), ('Finalizada', 'Finalizada')], default='Aberta', max_length=25, verbose_name='Status'),
        ),
    ]
