# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0024_auto_20180914_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='situacao',
            field=models.CharField(default='M', max_length=100),
        ),
    ]
